### ISSUE TITLE
Remote resource not found: https://api.github.com/repos/nextflow-io/table_annovar-nf/contents/main.nf

### ISSUE THREAD

**Issue by arronlacey** [IARCbioinfo/table_annovar-nf#3]
$nextflow run table_annovar-nf -r v1.0 -profile singularity --example VCF/ --table_extension vcf
N E X T F L O W  ~  version 21.04.3
Pulling nextflow-io/table_annovar-nf ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nextflow-io/table_annovar-nf/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nextflow-io/table_annovar-nf/contents/main.nf

**Comment by nalcala** [comment]
Hi @arronlacey , I think what is happening to you is that you are not using the full name of the pipeline linking to the github repo, thus nextflow tries to pull it from their own nextflow-io github and it doesn't find it. Try `nextflow run IARCbioinfo/table_annovar-nf` instead

**Comment by arronlacey** [comment]
ah yes thanks very much!
